; ReSNM.cmd SETTINGS
; Original SNMsynth forum thread: https://msfn.org/board/topic/127790-silent-net-maker-synthesized-20100118-w2kxp2k3-x86/
; Unless expressely stated, settings have one working value - "1" - meaning "process only if package is present."

; ----- PROCESS MAIN PACKAGES
; These settings control processing for .NET 1.1 (dotnetfx.exe), 2.0 SP2 (NetFx20SP2_x86.exe or dotnetfx35.exe),
; 3.0 SP2 (dotnetfx35.exe), and 3.5 SP1 (dotnetfx35.exe).
; If both possible sources for 2.0 SP2 are present use the following settings to choose which one to process.

PROCESSDNF11=1
PROCESSDNF20=
PROCESSDNF3520=1
PROCESSDNF3530=1
PROCESSDNF3535=1

; For the following three sections, if the variable is set to "1", then the following component will be removed.

; ----- SUBCOMPONENTS OF .NETFX 2.0 SP2 --->> CAUTION ADVISED
; -- RMDNF20VC8RUNTIME - remove outdated Visual C++ 8 Runtime libraries. VC8 has to be installed prior to 2.0 SP2.
; -- RMDNF20OFFICE2K3DEBUGGER - remove outdated Office 2K3 debugger from 2.0 SP2. Office 2003 SP3 includes a newer version.

RMDNF20VC8RUNTIME=1
RMDNF20OFFICE2K3DEBUGGER=1

; ----- SUBCOMPONENTS OF .NETFX 3.0 SP2 --->> CAUTION ADVISED
; -- RMDNF30RGBRASTERIZER - remove DirectX 9 RGB rasterizer. There is no updated source to replace it with, though.
; -- RMDNF30WIC - remove outdated Win Imaging Component (WIC) from 3.0 SP2 (XP SP3 also provides an outdated WIC version). WIC has to be
;         installed prior to 3.0 SP2.
; -- RMDNF30MSXML6 - remove MSXML6 component. ReSMN can incorporate MSXML6 updates, however. MSXML6 has to then be installed prior to 3.0 SP2.
;         It only makes sense to keep and update the msxml6.dll included with 3.0 SP2 if targerting XP SP2, since that OS does not
;         have any msxml6.dll stock. I cannot speak to 2K3's situation.
; -- RMDNF30XPS - remove XPS component. ReSMN can incorporate XPS updates, however. XPS has to be installed prior to 3.0 SP2.

RMDNF30RGBRASTERIZER=
RMDNF30WIC=1
RMDNF30MSXML6=1
RMDNF30XPS=

; ----- SUBCOMPONENTS OF .NETFX 3.5 SP1 --->> CAUTION ADVISED
; -- RMDNF35VC9RUNTIME - remove outdated Visual C++ 9 runtime libraries. VC9 has to be installed prior to 3.5 SP1.
; -- RMDNF35FFXBAPPLUGIN - remove Windows Presentation Foundation plugin (XBAP) for supported Firefox browsers.
; -- RMDNF35FFCLICKONCEEXT - remove .NET FX Assistant 1.0 Firefox extension (ClickOnce) from 3.5 SP1.

RMDNF35VC9RUNTIME=1
RMDNF35FFXBAPPLUGIN=1
RMDNF35FFCLICKONCEEXT=1

; ----- PROCESS LANGUAGE PACKS
; "1" here means "yes" only if both framework and langpack are present and set to be processed. These settings control langpacks
; processing for .NET 1.1 (langpack*.exe, you will have to denote them individually), .NET 2.0 SP2 (NetFx20SP2_x86??.exe), and
; 3.5 SP1 langpacks (dotnetfx35langpack_x86??.exe).

PROCESSLNGDNF11=
PROCESSLNGDNF20=
PROCESSLNGDNF3520=
PROCESSLNGDNF3530=
PROCESSLNGDNF3535=

; ----- GLOBAL
; -- TARGETOS (2K, XP, 2K3) - set which Windows version to target with your custom installers/add-ons.
;         Installers/add-ons are geared for one target OS version and are not compatible with others.
; -- T13ADDONS - output T-13 nLite/RVMI add-ons. Does not create normal installers (can be extracted from them).
; -- ROEADDONS - output RunOnceEx nLite/RVMI add-ons. Does not create normal installers (can be extracted from them).
; -- ALSOINSTALLERS - if T13ADDONS and/or ROEADDONS, also output normal installers.
; -- MERGEFXS - merge all frameworks being processed into one installer/add-on.
; -- SILENT - makes "quiet" installers/add-ons instead of "passive" ones by default. The verbosity of installers/add-ons can be modified
;         at runtime with flags passed to the installer.
; -- COMPLEVEL (ULTRA, NORMAL, NO) - set compression level (default "ULTRA"). "NORMAL" or "NO" are useful for low-RAM or slow machines.
;         In spite of this setting, you can restart the compression subprocess mid-process, changing the compression ratio.

TARGETOS=XP
T13ADDONS=
ROEADDONS=
ALSOINSTALLERS=
MERGEFXS=1
SILENT=
COMPLEVEL=ULTRA
